# environment.yml

name: /Users/lui/Desktop/ailabs/.conda
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - abseil-cpp=20211102.0=hc377ac9_0
  - absl-py=2.1.0=py311hca03da5_0
  - aiohappyeyeballs=2.4.4=py311hca03da5_0
  - aiohttp=3.11.10=py311h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=py_0
  - attrs=24.3.0=py311hca03da5_0
  - beautifulsoup4=4.12.3=py311hca03da5_0
  - blas=1.0=openblas
  - blinker=1.9.0=py311hca03da5_0
  - bottleneck=1.4.2=py311hb9f6ed7_0
  - brotli-python=1.0.9=py311h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.2.25=hca03da5_0
  - cachetools=5.5.1=py311hca03da5_0
  - certifi=2025.1.31=py311hca03da5_0
  - cffi=1.17.1=py311h3eb5a62_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py311hca03da5_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cryptography=41.0.3=py311h3c57c4d_0
  - debugpy=1.8.11=py311h313beb8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dm-tree=0.1.7=py311h313beb8_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - flatbuffers=24.3.25=h313beb8_0
  - frozenlist=1.5.0=py311h80987f9_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.2=h80987f9_0
  - google-auth=2.38.0=py311hca03da5_0
  - google-auth-oauthlib=0.5.2=py311hca03da5_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.48.2=h877324c_0
  - grpcio=1.48.2=py311h877324c_0
  - h5py=3.12.1=py311h8456320_0
  - hdf5=1.12.1=h160e8cb_2
  - icu=68.1=hc377ac9_0
  - idna=3.7=py311hca03da5_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.32.0=pyh907856f_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.4.2=py311hca03da5_0
  - jpeg=9e=h80987f9_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keras=2.12.0=py311hca03da5_0
  - keras-core=0.1.7=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - keras-tuner=1.4.7=pyhd8ed1ab_1
  - krb5=1.20.1=h8380606_1
  - kt-legacy=1.0.5=py311hca03da5_0
  - libcurl=8.2.1=h0f1d93c_0
  - libcxx=19.1.7=ha82da77_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libnghttp2=1.52.0=h10c0552_1
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h27ca646_1
  - libssh2=1.10.0=h449679c_2
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown=3.4.1=py311hca03da5_0
  - markdown-it-py=2.2.0=py311hca03da5_1
  - markupsafe=3.0.2=py311h80987f9_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.0=py311hca03da5_0
  - ml_dtypes=0.5.0=py311h313beb8_0
  - multidict=6.1.0=py311h80987f9_0
  - namex=0.0.7=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nltk=3.9.1=py311hca03da5_0
  - numexpr=2.10.1=py311h5d9532f_0
  - numpy=1.23.5=py311hb2c0538_0
  - numpy-base=1.23.5=py311h9eb1c70_0
  - oauthlib=3.2.2=py311hca03da5_0
  - openssl=1.1.1w=h1a28f6b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.12.1=py311h48ca7d4_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py311hcf29cfe_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py311hca03da5_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - propcache=0.2.0=py311h80987f9_0
  - protobuf=3.20.3=py311h313beb8_0
  - psutil=5.9.0=py311h80987f9_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyjwt=2.10.1=py311hca03da5_0
  - pyopenssl=23.2.0=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.5=hc0d8a6c_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-flatbuffers=24.3.25=py311hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py311hca03da5_0
  - pyzmq=26.2.0=py311h313beb8_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - regex=2024.11.6=py311h80987f9_0
  - requests=2.32.3=py311hca03da5_1
  - requests-oauthlib=2.0.0=py311hca03da5_0
  - rich=13.9.4=py311hca03da5_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.6.1=py311h313beb8_0
  - scipy=1.15.1=py311hac8794a_0
  - setuptools=75.8.0=py311hca03da5_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h313beb8_0
  - soupsieve=2.5=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tensorboard=2.12.1=py311hca03da5_0
  - tensorboard-data-server=0.7.0=py311ha6e5c4f_1
  - tensorboard-plugin-wit=1.8.1=py311hca03da5_0
  - tensorflow=2.12.0=eigen_py311h689d69b_0
  - tensorflow-base=2.12.0=eigen_py311h0a52ebb_0
  - tensorflow-estimator=2.12.0=py311hca03da5_0
  - termcolor=2.1.0=py311hca03da5_0
  - threadpoolctl=3.5.0=py311hb6e6a13_0
  - tk=8.6.14=h6ba3021_0
  - tornado=6.4.2=py311h80987f9_0
  - tqdm=4.67.1=py311hb6e6a13_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py311hca03da5_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - werkzeug=3.1.3=py311hca03da5_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - wikipedia=1.4.0=pyhd8ed1ab_3
  - wrapt=1.17.0=py311h80987f9_0
  - xz=5.6.4=h80987f9_1
  - yarl=1.18.0=py311h80987f9_0
  - zeromq=4.3.5=hebf3989_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - astor==0.8.1
      - fastjsonschema==2.21.1
      - imageio==2.37.0
      - jinja2==3.1.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - nbformat==5.10.4
      - pillow==11.1.0
      - pyaudio==0.2.14
      - pydatalog==0.17.4
      - python-aiml==0.9.3
      - pyyaml==6.0.2
      - referencing==0.36.2
      - rpds-py==0.23.1
      - scikit-fuzzy==0.5.0
      - speechrecognition==3.14.2
      - tensorflow-docs==2025.2.19.33219
prefix: /Users/lui/Desktop/ailabs/.conda
